import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    screens: { 'xs': '475px', 'sm': '640px', 'md': '768px', 'lg': '1024px', 'xl': '1280px', '2xl': '1536px' },
    extend: {
      fontFamily: {
        sans: ['Montserrat', 'system-ui', 'sans-serif'],
        display: ['Montserrat', 'system-ui', 'sans-serif'],
        headline: ['Montserrat', 'system-ui', 'sans-serif'],
        mono: ['Montserrat', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))", input: "hsl(var(--input))", ring: "hsl(var(--ring))",
        background: "hsl(var(--background))", foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))", foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))", "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))", "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))", ring: "hsl(var(--sidebar-ring))",
        },
        neo: {
          blue: "hsl(var(--neo-blue))", "blue-glow": "hsl(var(--neo-blue-glow))",
          dark: "hsl(var(--neo-dark))", "dark-lighter": "hsl(var(--neo-dark-lighter))",
          glass: "hsl(var(--neo-glass))", "glass-border": "hsl(var(--neo-glass-border))",
          "text-muted": "hsl(var(--neo-text-muted))", success: "hsl(var(--neo-success))",
          warning: "hsl(var(--neo-warning))", purple: "hsl(var(--neo-purple))", cyan: "hsl(var(--neo-cyan))",
        },
        "brand-red": {
          50: "hsl(356 93% 96%)", 100: "hsl(355 77% 87%)", 200: "hsl(356 73% 80%)",
          300: "hsl(356 74% 71%)", 400: "hsl(356 76% 65%)", 500: "hsl(355 78% 56%)",
          600: "hsl(355 64% 51%)", 700: "hsl(355 61% 40%)", 800: "hsl(355 73% 31%)",
          900: "hsl(356 60% 25%)",
        },
        "deep-red": {
          50: "hsl(356 70% 92%)", 100: "hsl(356 60% 83%)", 200: "hsl(356 52% 75%)",
          300: "hsl(356 52% 63%)", 400: "hsl(356 58% 55%)", 500: "hsl(356 73% 44%)",
          600: "hsl(356 74% 40%)", 700: "hsl(355 74% 31%)", 800: "hsl(356 80% 26%)",
          900: "hsl(356 76% 20%)",
        },
        "surface": {
          50: "hsl(240 3% 91%)", 100: "hsl(240 4% 73%)", 200: "hsl(240 6% 61%)",
          300: "hsl(240 6% 43%)", 400: "hsl(240 10% 31%)", 500: "hsl(240 28% 14%)",
          600: "hsl(240 27% 13%)", 700: "hsl(240 29% 10%)", 800: "hsl(240 28% 8%)",
          900: "hsl(240 27% 6%)",
        },
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)", "2xl": "1rem", "3xl": "1.5rem" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        pulse: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.5" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "fade-in-up": { from: { opacity: "0", transform: "translateY(30px) scale(0.97)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
        "pull-in": { "0%": { opacity: "0", transform: "scale(0.85) translateY(40px)", filter: "blur(8px)" }, "100%": { opacity: "1", transform: "scale(1) translateY(0)", filter: "blur(0px)" } },
        "pull-in-left": { "0%": { opacity: "0", transform: "translateX(-60px) scale(0.9)", filter: "blur(6px)" }, "100%": { opacity: "1", transform: "translateX(0) scale(1)", filter: "blur(0px)" } },
        "pull-in-right": { "0%": { opacity: "0", transform: "translateX(60px) scale(0.9)", filter: "blur(6px)" }, "100%": { opacity: "1", transform: "translateX(0) scale(1)", filter: "blur(0px)" } },
        "float": { "0%, 100%": { transform: "translateY(0px) rotate(0deg)" }, "50%": { transform: "translateY(-20px) rotate(3deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out", "accordion-up": "accordion-up 0.2s ease-out",
        "spin-slow": "spin-slow 3s linear infinite",
        "fade-in-up": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pull-in": "pull-in 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "pull-in-left": "pull-in-left 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "pull-in-right": "pull-in-right 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "float": "float 6s ease-in-out infinite",
      },
      backgroundImage: {
        "neo-gradient": "linear-gradient(145deg, hsl(252 100% 4%) 0%, hsl(240 29% 10%) 100%)",
        "neo-card-gradient": "linear-gradient(145deg, hsl(240 29% 10% / 0.95) 0%, hsl(252 100% 4% / 0.9) 100%)",
        "neo-blue-gradient": "linear-gradient(135deg, hsl(var(--neo-blue)) 0%, hsl(var(--neo-blue-glow)) 100%)",
        "neo-warmth": "linear-gradient(135deg, hsl(355 78% 56%) 0%, hsl(356 73% 44%) 100%)",
        "neo-premium": "linear-gradient(135deg, hsl(var(--neo-blue)) 0%, hsl(var(--neo-cyan)) 50%, hsl(var(--neo-blue)) 100%)",
        "neo-radial": "radial-gradient(ellipse at center, hsl(var(--primary) / 0.15) 0%, transparent 70%)",
      },
      boxShadow: {
        "neo-glow": "0 0 20px hsl(355 78% 56% / 0.4), 0 0 40px hsl(355 78% 56% / 0.2), 0 20px 40px hsl(0 0% 0% / 0.5)",
        "neo-glow-lg": "0 0 32px hsl(355 78% 56% / 0.5), 0 0 64px hsl(355 78% 56% / 0.3), 0 28px 56px hsl(0 0% 0% / 0.6)",
        "neo-glow-intense": "0 0 48px hsl(355 78% 56% / 0.6), 0 0 80px hsl(355 78% 56% / 0.3)",
        "neo-card": "0 8px 32px hsl(0 0% 0% / 0.5), inset 0 1px 0 0 hsl(0 0% 100% / 0.04)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
