import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    screens: { 'xs': '475px', 'sm': '640px', 'md': '768px', 'lg': '1024px', 'xl': '1280px', '2xl': '1536px' },
    extend: {
      fontFamily: {
        sans: ['Montserrat', 'system-ui', 'sans-serif'],
        display: ['Montserrat', 'system-ui', 'sans-serif'],
        headline: ['Montserrat', 'system-ui', 'sans-serif'],
        mono: ['Montserrat', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))", input: "hsl(var(--input))", ring: "hsl(var(--ring))",
        background: "hsl(var(--background))", foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))", foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))", "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))", "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))", ring: "hsl(var(--sidebar-ring))",
        },
        neo: {
          red: "hsl(var(--neo-red))", "red-glow": "hsl(var(--neo-red-glow))",
          dark: "hsl(var(--neo-dark))", "dark-lighter": "hsl(var(--neo-dark-lighter))",
          glass: "hsl(var(--neo-glass))", "glass-border": "hsl(var(--neo-glass-border))",
          "text-muted": "hsl(var(--neo-text-muted))", success: "hsl(var(--neo-success))",
          warning: "hsl(var(--neo-warning))", purple: "hsl(var(--neo-purple))", blue: "hsl(var(--neo-blue))",
        },
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)", "2xl": "1rem", "3xl": "1.5rem" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        pulse: { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.5" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "fade-in-up": { from: { opacity: "0", transform: "translateY(30px) scale(0.97)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
        "pull-in": { "0%": { opacity: "0", transform: "scale(0.85) translateY(40px)", filter: "blur(8px)" }, "100%": { opacity: "1", transform: "scale(1) translateY(0)", filter: "blur(0px)" } },
        "pull-in-left": { "0%": { opacity: "0", transform: "translateX(-60px) scale(0.9)", filter: "blur(6px)" }, "100%": { opacity: "1", transform: "translateX(0) scale(1)", filter: "blur(0px)" } },
        "pull-in-right": { "0%": { opacity: "0", transform: "translateX(60px) scale(0.9)", filter: "blur(6px)" }, "100%": { opacity: "1", transform: "translateX(0) scale(1)", filter: "blur(0px)" } },
        "float": { "0%, 100%": { transform: "translateY(0px) rotate(0deg)" }, "50%": { transform: "translateY(-20px) rotate(3deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out", "accordion-up": "accordion-up 0.2s ease-out",
        "spin-slow": "spin-slow 3s linear infinite",
        "fade-in-up": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pull-in": "pull-in 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "pull-in-left": "pull-in-left 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "pull-in-right": "pull-in-right 0.7s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "float": "float 6s ease-in-out infinite",
      },
      backgroundImage: {
        "neo-gradient": "linear-gradient(145deg, hsl(0 0% 3%) 0%, hsl(0 0% 7%) 100%)",
        "neo-card-gradient": "linear-gradient(145deg, hsl(0 0% 7% / 0.95) 0%, hsl(0 0% 4% / 0.9) 100%)",
        "neo-red-gradient": "linear-gradient(135deg, hsl(var(--neo-red)) 0%, hsl(var(--neo-red-glow)) 100%)",
        "neo-warmth": "linear-gradient(135deg, hsl(0 85% 55%) 0%, hsl(355 90% 60%) 100%)",
        "neo-premium": "linear-gradient(135deg, hsl(var(--neo-red)) 0%, hsl(var(--accent)) 50%, hsl(var(--neo-red)) 100%)",
        "neo-radial": "radial-gradient(ellipse at center, hsl(var(--primary) / 0.2) 0%, transparent 70%)",
      },
      boxShadow: {
        "neo-glow": "0 0 25px hsl(var(--neo-red) / 0.5), 0 0 50px hsl(var(--neo-red) / 0.3), 0 25px 50px hsl(0 0% 0% / 0.6)",
        "neo-glow-lg": "0 0 40px hsl(var(--neo-red) / 0.6), 0 0 80px hsl(var(--neo-red) / 0.4), 0 35px 70px hsl(0 0% 0% / 0.7)",
        "neo-glow-intense": "0 0 60px hsl(var(--neo-red) / 0.7), 0 0 100px hsl(var(--neo-red) / 0.5), 0 0 150px hsl(var(--neo-red) / 0.3)",
        "neo-card": "0 0 30px hsl(var(--neo-red) / 0.1), 0 30px 60px hsl(0 0% 0% / 0.8), inset 0 1px 0 0 hsl(0 0% 100% / 0.04)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
